apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-deployment
  labels:
      {{- /*app: {{ $.Values.labels.app | quote}} */}}
    {{- include "labels" . | nindent 4}}

spec:
  replicas: {{ $.Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ $.Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ $.Values.labels.app }}
    spec:
      containers:
        - name: {{ $.Release.Name }}-container
          image: {{ $.Values.deployment.container.image }}
          ports:
            - containerPort: {{ $.Values.deployment.container.port }}